### ISSUE TITLE
FuzzyWuzzy License

### ISSUE THREAD

**Issue by maxbachmann** [suvansh-rana/developer-search#5]
FuzzyWuzzy is GPL licensed which forces any project using it to be GPL licensed aswell. So you should either change the project license, or use fuzzywuzzy==0.1 (Thats the only correctly MIT Licensed release of FuzzyWuzzy since they started using GPL licensed code afterwards).
As an alternative for FuzzyWuzzy you could use [RapidFuzz](https://github.com/maxbachmann/rapidfuzz) (I am the author), which is MIT Licensed and faster than FuzzyWuzzy.

**Comment by suvansh-rana** [comment]
@maxbachmann thanks for raising the issue :+1:. I have migrated the project to RapidFuzz. You can see the changes [here](https://github.com/suvansh-rana/developer-search/commit/61f6e5be959c7fb765b112609895d39e42782b58).
